CREATE TABLE rooms (
    id VARCHAR(255)
    user1_id INT
    user2_id INT
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)